const STOP = new Set(`a an the and or of to for from in on at by with without is are was were be been being do does did has have had shall should must may can could would will as that this these those it its their there whether if when while during before after including include includes established ensure verify check review procedure procedures requirement requirements system systems control controls company vessel ship ships onboard relevant current accordance according all any each which what who how`.split(/\s+/));

const HIGH_RISK = /enclosed|confined|mooring|navigation|ecdis|steering|emergency|fire|gas|cargo|permit|hot work|lifesaving|life.?boat|critical machinery|alarm|bridge|engine|tank entry/i;

const BASIC_SYNONYMS = [
  ['ptw','permit','work authorization'],['ecdis','electronic chart','electronic charts'],['sms','safety management system'],['pms','planned maintenance system'],['c/o','chief officer'],['2/o','second officer'],['o2','oxygen'],['lel','flammable gas'],
];
const EXPANDED_SYNONYMS = [
  ...BASIC_SYNONYMS,
  ['enclosed space','confined space','restricted compartment','confined compartment','tank entry'],['gas testing','atmosphere testing','atmospheric testing','atmospheric measurement','gas measurement'],['permit to work','work permit','work authorization','entry permit'],['rescue arrangements','rescue readiness','standby rescue','rescue equipment'],['continuous monitoring','continuous atmosphere monitoring','continuous gas monitoring'],['mooring','winch','brake rendering','mooring lines','ropes'],['navigation','passage plan','voyage plan','bridge team','ecdis'],['fire safety','firefighting','fire fighting','fire pump','fire detection'],['emergency response','contingency','muster','emergency preparedness'],['steering gear','emergency steering','steering system'],['lifesaving','life saving','lsa','lifeboat','rescue boat','liferaft'],['cargo operation','cargo operations','loading','discharging','manifold','cargo control'],['ballast water','bwts','ballast water treatment','d-2','d2 standard'],
];

const clean = (v='') => String(v ?? '').trim();
const normalize = v => clean(v).toLowerCase().replace(/[‐‑–—]/g,'-').replace(/[^a-z0-9./+\-\s]/g,' ').replace(/\s+/g,' ').trim();
function stem(token){let t=token.toLowerCase();if(t.length>5&&t.endsWith('ies'))t=t.slice(0,-3)+'y';else if(t.length>5&&t.endsWith('ing'))t=t.slice(0,-3);else if(t.length>4&&t.endsWith('ed'))t=t.slice(0,-2);else if(t.length>4&&t.endsWith('es'))t=t.slice(0,-2);else if(t.length>3&&t.endsWith('s'))t=t.slice(0,-1);return t;}
function tokens(text){return normalize(text).split(/\s+/).map(stem).filter(t=>t.length>2&&!STOP.has(t));}
function unique(list){return [...new Set(list.filter(Boolean))];}
function phrases(text){const words=normalize(text).split(' ').filter(Boolean),out=[];for(let size=4;size>=2;size--)for(let i=0;i<=words.length-size;i++){const phrase=words.slice(i,i+size).join(' ');if(tokens(phrase).length>=2)out.push(phrase);}return unique(out).slice(0,36);}
function synonymsFor(text,mode='basic'){const n=normalize(text),groups=mode==='expanded'?EXPANDED_SYNONYMS:BASIC_SYNONYMS,additions=[];for(const group of groups)if(group.some(term=>n.includes(normalize(term))))additions.push(...group);return unique(additions);}
function buildWeightedQuery(item,synonymMode='basic'){const parts=[{text:item.question,weight:3},{text:item.section,weight:4},{text:item.guidance,weight:1.5},{text:item.risk,weight:.75}],weights=new Map();for(const part of parts)for(const t of tokens(part.text))weights.set(t,(weights.get(t)||0)+part.weight);const baseText=parts.map(p=>p.text||'').join(' ');for(const synonym of synonymsFor(baseText,synonymMode))for(const t of tokens(synonym))weights.set(t,Math.max(weights.get(t)||0,synonymMode==='expanded'?1.65:1.15));return{weights,phraseList:phrases(`${item.section||''} ${item.question||''}`),baseText};}
export function buildPageIndex(pages=[]){return pages.map(page=>{const textNorm=normalize(`${page.heading||''} ${page.section||''} ${page.text||''}`);return{...page,_searchIndex:{textNorm,tokenSet:new Set(tokens(textNorm)),headingTokenSet:new Set(tokens(`${page.heading||''} ${page.section||''}`))}};});}
function pageScore(query,page){const textNorm=page._searchIndex?.textNorm||normalize(`${page.heading||''} ${page.section||''} ${page.text||''}`),pageTokens=page._searchIndex?.tokenSet||new Set(tokens(textNorm)),headingTokens=page._searchIndex?.headingTokenSet||new Set(tokens(`${page.heading||''} ${page.section||''}`));let possible=0,matched=0,headingMatched=0;for(const [token,weight] of query.weights){possible+=weight;if(pageTokens.has(token))matched+=weight;if(headingTokens.has(token))headingMatched+=weight;}const coverage=possible?matched/possible:0,headingCoverage=possible?headingMatched/possible:0;let phraseBonus=0;for(const p of query.phraseList)if(p.length>8&&textNorm.includes(normalize(p)))phraseBonus+=3.5;phraseBonus=Math.min(17,phraseBonus);const sectionText=normalize(page.section||''),itemSection=normalize(query.itemSection||''),sectionBonus=itemSection&&sectionText&&(sectionText===itemSection||itemSection.includes(sectionText))?6:0;return{raw:Number(Math.min(100,coverage*72+headingCoverage*22+phraseBonus+sectionBonus).toFixed(2)),coverage,matchedWeight:matched,possibleWeight:possible};}
function excerpt(text,queryTokens,max=420){const raw=clean(text);if(raw.length<=max)return raw;const lower=raw.toLowerCase();let at=-1;for(const t of queryTokens){const i=lower.indexOf(t.toLowerCase());if(i>=0&&(at<0||i<at))at=i;}if(at<0)return raw.slice(0,max)+'…';const start=Math.max(0,at-110),end=Math.min(raw.length,start+max);return(start>0?'…':'')+raw.slice(start,end)+(end<raw.length?'…':'');}
function conceptTokens(item){return unique([...tokens(item.question||''),...tokens(item.section||''),...tokens(item.guidance||'')]).filter(t=>t.length>=4).slice(0,30);}
function explainCoverage(item,matches){const concepts=conceptTokens(item),set=new Set(tokens(matches.map(m=>`${m.heading||''} ${m.text||''}`).join(' ')));return{covered:concepts.filter(t=>set.has(t)),unsupported:concepts.filter(t=>!set.has(t))};}
function riskPriority(item,classification){const high=HIGH_RISK.test(`${item.section||''} ${item.question||''} ${item.guidance||''}`);if(high&&['No Relevant Control Located','Possible Gap'].includes(classification))return'Critical';if(['No Relevant Control Located','Possible Gap'].includes(classification))return'High';if(high&&classification==='Partial Coverage')return'High';if(classification==='Partial Coverage')return'Medium';if(classification==='Needs Auditor Review')return high?'High':'Medium';return'Low';}
function nextActionsFor(classification){if(classification==='No Relevant Control Located')return['Search related SMS manuals/forms and cross-references','Ask the company to identify the governing controlled procedure','Verify applicability before treating the absence as a concern'];if(classification==='Possible Gap')return['Review the matched SMS pages in full context','Search related forms, appendices and cross-referenced procedures','Challenge the gap before accepting it for auditor review'];if(classification==='Partial Coverage')return['Review unsupported SIRE concepts against related SMS sections','Check referenced forms/checklists for the missing control elements','Confirm the current controlled revision'];if(classification==='Needs Auditor Review')return['Compare competing SMS matches and identify the governing control','Confirm the applicable revision and scope','Record the auditor judgement with source page references'];return['Open the matched SMS pages and verify context','Confirm the current revision and applicability','Continue with onboard evidence verification separately'];}
export function mapSireItem(item,pages=[],options={}){const synonymMode=options.synonymMode||'basic',query=buildWeightedQuery(item,synonymMode);query.itemSection=item.section||'';const minScore=Number.isFinite(options.minScore)?options.minScore:(synonymMode==='expanded'?17:22),scored=pages.map(page=>({...page,...pageScore(query,page)})).sort((a,b)=>b.raw-a.raw);let candidates=scored.filter(x=>x.raw>=minScore).slice(0,4);if(candidates.length){const selectedNums=new Set(candidates.map(c=>c.pageNumber)),top=candidates[0];for(const page of pages){if(selectedNums.has(page.pageNumber))continue;if(Math.abs(Number(page.pageNumber)-Number(top.pageNumber))===1){const sameSection=top.section&&page.section&&normalize(top.section)===normalize(page.section),continuation=/continued|continuation/i.test(page.heading||'');if(sameSection||continuation){const s=pageScore(query,page);candidates.push({...page,...s,adjacent:true});selectedNums.add(page.pageNumber);}}}}candidates.sort((a,b)=>b.raw-a.raw);if(!candidates.length)return{...item,classification:'No Relevant Control Located',confidence:0,matches:[],coveredConcepts:[],unsupportedConcepts:conceptTokens(item),priority:riskPriority(item,'No Relevant Control Located'),nextActions:nextActionsFor('No Relevant Control Located'),coverageNote:'Document coverage only — not a compliance conclusion.',challengeApplied:false};const matches=candidates.slice(0,5).map(c=>({pageNumber:c.pageNumber,heading:c.heading||'',section:c.section||'',score:Math.round(c.raw),adjacent:Boolean(c.adjacent),excerpt:excerpt(c.text,[...query.weights.keys()]),text:c.text||'',why:c.adjacent?'Adjacent page in the same procedure section':`Weighted SIRE/SMS concept match ${Math.round(c.raw)}%`}));const{covered,unsupported}=explainCoverage(item,matches),conceptCount=covered.length+unsupported.length,conceptCoverage=conceptCount?covered.length/conceptCount:0,topScore=matches[0]?.score||0,secondScore=matches[1]?.score||0,ambiguity=matches.length>1&&topScore<52&&Math.abs(topScore-secondScore)<=5&&matches[0].section!==matches[1].section;let classification;if(ambiguity)classification='Needs Auditor Review';else if(topScore>=58&&conceptCoverage>=.72)classification='Strong Coverage';else if(topScore>=34&&conceptCoverage>=.45)classification='Partial Coverage';else classification='Possible Gap';const confidence=Math.max(1,Math.min(99,Math.round(topScore*.72+conceptCoverage*28)));return{...item,classification,confidence,matches,coveredConcepts:covered,unsupportedConcepts:unsupported,priority:riskPriority(item,classification),nextActions:nextActionsFor(classification),coverageNote:'Document coverage only — not a compliance conclusion.',challengeApplied:false};}
export function challengeMapping(item,pages,currentResult={}){const challenged=mapSireItem(item,pages,{synonymMode:'expanded',minScore:14});return{...challenged,challengeApplied:true,challengePreviousClassification:currentResult.classification||null,challengeSummary:challenged.classification===currentResult.classification?'Broader search did not materially change the document-coverage classification.':`Broader search changed document coverage from ${currentResult.classification||'unclassified'} to ${challenged.classification}. Auditor review is required.`};}
export function rankResults(results=[]){const p={Critical:5,High:4,Medium:3,Low:2},c={'No Relevant Control Located':5,'Possible Gap':4,'Partial Coverage':3,'Needs Auditor Review':2,'Strong Coverage':1};return[...results].sort((a,b)=>(p[b.priority]||0)-(p[a.priority]||0)||(c[b.classification]||0)-(c[a.classification]||0)||(a.confidence||0)-(b.confidence||0));}
export const __test={normalize,tokens,synonymsFor,buildWeightedQuery,pageScore,conceptTokens};
