import test from 'node:test';
import assert from 'node:assert/strict';
import { mapSireItem, challengeMapping, rankResults } from '../core/mapper.js';

const pages = [
  { pageNumber: 10, heading: 'Enclosed Space Entry', section: '7.4.2', text: 'Enclosed space entry requires a permit to work before entry. Atmosphere shall be tested for oxygen, flammable gas and toxic gas. A responsible officer shall supervise entry.' },
  { pageNumber: 11, heading: 'Enclosed Space Entry continued', section: '7.4.2', text: 'Rescue equipment and communication arrangements shall be ready. Continuous atmosphere monitoring is required while personnel remain inside the space.' },
  { pageNumber: 40, heading: 'Mooring Operations', section: '5.3', text: 'Mooring winch brakes shall be tested annually and rendering settings verified. Mooring lines shall be inspected before use.' },
  { pageNumber: 55, heading: 'Bridge Navigation', section: '6.2', text: 'Passage planning shall include under keel clearance, ECDIS route validation, chart updates and bridge team briefing.' },
  { pageNumber: 70, heading: 'Restricted compartment access', section: '8.2', text: 'Access to confined compartments requires atmospheric measurement, work authorization and standby rescue arrangements.' },
];
const sire = (overrides={}) => ({reference:'5.4.3',section:'Enclosed Space Entry',question:'Are procedures established for enclosed space entry including permit to work, atmosphere testing, rescue arrangements and continuous monitoring?',guidance:'Verify permits, gas testing and rescue readiness.',rank:'Chief Officer',applicability:'All vessels',...overrides});

test('maps a SIRE item to the correct SMS pages and adjacent continuation page',()=>{const result=mapSireItem(sire(),pages);assert.ok(result.matches.length>=2);assert.equal(result.matches[0].pageNumber,10);assert.ok(result.matches.some(m=>m.pageNumber===11));assert.ok(['Strong Coverage','Partial Coverage'].includes(result.classification));assert.ok(result.confidence>=60);});
test('classifies incomplete relevant control as partial or possible gap instead of compliant',()=>{const result=mapSireItem(sire({question:'Are enclosed space procedures established including permit, atmosphere testing, rescue, continuous monitoring and periodic communication checks?'}),[pages[0]]);assert.ok(['Partial Coverage','Possible Gap'].includes(result.classification));assert.ok(result.unsupportedConcepts.length>0);assert.doesNotMatch(JSON.stringify(result),/non-?compliant|compliant/i);});
test('returns No Relevant Control Located when no candidate passes retrieval threshold',()=>{const result=mapSireItem(sire({section:'Ballast Water',question:'Is ballast water treatment operated and sampled in accordance with the ballast water management plan?',guidance:'Check BWTS records and D-2 sampling.'}),pages);assert.equal(result.classification,'No Relevant Control Located');assert.equal(result.matches.length,0);});
test('challenge search can locate alternate terminology missed by initial query',()=>{const item=sire({section:'Enclosed Space',question:'Is enclosed space access controlled by gas testing, permit and rescue standby?',guidance:''});const initial=mapSireItem(item,[pages[4]],{synonymMode:'basic',minScore:36});assert.equal(initial.classification,'No Relevant Control Located');const challenged=challengeMapping(item,[pages[4]],initial);assert.notEqual(challenged.classification,'No Relevant Control Located');assert.equal(challenged.matches[0].pageNumber,70);assert.equal(challenged.challengeApplied,true);});
test('risk-attention ranking brings high-attention gaps ahead of ordinary partial coverage',()=>{const ranked=rankResults([{reference:'1',section:'Administration',classification:'Partial Coverage',confidence:50,priority:'Medium'},{reference:'2',section:'Mooring Operations',classification:'Possible Gap',confidence:30,priority:'Critical'},{reference:'3',section:'Crew records',classification:'No Relevant Control Located',confidence:0,priority:'High'}]);assert.equal(ranked[0].reference,'2');});
