import { inferColumnMapping } from '../core/excel-schema.js';

export const PARSER_ERRORS = Object.freeze({PASSWORD:'PASSWORD_PROTECTED_PDF',IMAGE_ONLY:'IMAGE_ONLY_PDF',PDF_UNREADABLE:'PDF_UNREADABLE',WORKBOOK_UNREADABLE:'WORKBOOK_UNREADABLE',NO_USABLE_SHEETS:'NO_USABLE_SHEETS'});
export const RUNTIME_LIBRARIES = Object.freeze({pdfjs:'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.min.mjs',pdfWorker:'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.worker.min.mjs',xlsx:'https://cdn.jsdelivr.net/npm/sheetjs_xlsx@0.20.0/xlsx.mjs'});
const clean=v=>String(v??'').trim(),compact=v=>clean(v).replace(/\s+/g,' ');
export function parserError(code,message,cause){const err=new Error(message);err.code=code;if(cause)err.cause=cause;return err;}
export function detectHeaderRow(matrix=[]){const keywords=/question|requirement|guidance|section|chapter|rank|role|applicab|vessel|risk|reference|ref|no\.?|number/i;let best={headerRowIndex:0,score:-1,headers:[]};matrix.slice(0,15).forEach((row,index)=>{if(!Array.isArray(row))return;const cells=row.map(clean),nonEmpty=cells.filter(Boolean),keywordHits=nonEmpty.filter(v=>keywords.test(v)).length,textish=nonEmpty.filter(v=>/[A-Za-z]/.test(v)&&v.length<120).length,score=keywordHits*5+Math.min(nonEmpty.length,12)*1.2+textish*.6-(nonEmpty.length<=1?4:0);if(score>best.score)best={headerRowIndex:index,score,headers:cells};});return best;}
export function textItemsToLines(items=[]){const rows=[];let current=null;for(const item of items){const str=compact(item?.str);if(!str)continue;const y=Number(item?.transform?.[5]);if(!current||!Number.isFinite(y)||!Number.isFinite(current.y)||Math.abs(y-current.y)>2.2){current={y:Number.isFinite(y)?y:NaN,parts:[str]};rows.push(current);}else current.parts.push(str);}return rows.map(r=>compact(r.parts.join(' '))).filter(Boolean);}
export function detectPageMetadata(text=''){const lines=String(text).split(/\n+/).map(compact).filter(Boolean),sectionMatch=lines.slice(0,8).join(' ').match(/(?:section|chapter|clause)?\s*([0-9]+(?:\.[0-9]+){1,5}[A-Za-z]?)/i),section=sectionMatch?.[1]||'',headingLine=lines.find(line=>line.length>3&&line.length<150&&!/^page\s+\d+$/i.test(line)&&!/^revision\b/i.test(line)&&!/^effective\b/i.test(line))||'',revision=String(text).match(/\brev(?:ision)?\s*[:.\-]?\s*([A-Za-z0-9.\-]+)/i)?.[1]||'',effectiveDate=String(text).match(/\beffective(?:\s+date)?\s*[:.\-]?\s*([^\n]{4,40})/i)?.[1]?.trim()||'';return{section,heading:headingLine,revision,effectiveDate};}
async function loadPdfJs(){try{const pdfjs=await import(RUNTIME_LIBRARIES.pdfjs);if(pdfjs?.GlobalWorkerOptions)pdfjs.GlobalWorkerOptions.workerSrc=RUNTIME_LIBRARIES.pdfWorker;return pdfjs;}catch(error){throw parserError(PARSER_ERRORS.PDF_UNREADABLE,'AuditOS could not load the PDF parser. Check internet access and retry.',error);}}
async function loadXlsx(){try{return await import(RUNTIME_LIBRARIES.xlsx);}catch(error){throw parserError(PARSER_ERRORS.WORKBOOK_UNREADABLE,'AuditOS could not load the Excel parser. Check internet access and retry.',error);}}
async function fileArrayBuffer(file){if(file?.arrayBuffer)return file.arrayBuffer();if(file instanceof ArrayBuffer)return file;if(ArrayBuffer.isView(file))return file.buffer;throw new Error('Unsupported file object');}
export async function parseSmsPdf(file,onProgress=()=>{}){const pdfjs=await loadPdfJs();let pdf;try{pdf=await pdfjs.getDocument({data:await fileArrayBuffer(file)}).promise;}catch(error){const name=String(error?.name||''),message=String(error?.message||'');if(/password/i.test(name+message))throw parserError(PARSER_ERRORS.PASSWORD,'This PDF is password-protected. Upload an unlocked text-based SMS PDF.',error);throw parserError(PARSER_ERRORS.PDF_UNREADABLE,'AuditOS could not read this PDF.',error);}const pages=[];let extractedChars=0;for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){const page=await pdf.getPage(pageNumber),content=await page.getTextContent(),lines=textItemsToLines(content.items),text=lines.join('\n'),meta=detectPageMetadata(text);extractedChars+=text.length;pages.push({pageNumber,text,normalizedText:compact(text).toLowerCase(),...meta});onProgress({phase:'pdf',current:pageNumber,total:pdf.numPages,percent:Math.round(pageNumber/pdf.numPages*100)});if(pageNumber%8===0)await new Promise(resolve=>setTimeout(resolve,0));}const minimum=Math.max(80,pdf.numPages*28);if(extractedChars<minimum)throw parserError(PARSER_ERRORS.IMAGE_ONLY,'The PDF contains too little extractable text for reliable gap analysis. Upload a text-based/OCR-enabled SMS PDF.');return{name:file?.name||'SMS.pdf',pageCount:pdf.numPages,pages,extractedChars};}
export async function parseSireWorkbook(file){const XLSX=await loadXlsx();let workbook;try{workbook=XLSX.read(await fileArrayBuffer(file),{type:'array',cellDates:false,raw:false});}catch(error){throw parserError(PARSER_ERRORS.WORKBOOK_UNREADABLE,'AuditOS could not read this Excel workbook.',error);}const sheets=[];for(const name of workbook.SheetNames||[]){const ws=workbook.Sheets[name];if(!ws)continue;const matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false,blankrows:false});if(!Array.isArray(matrix)||matrix.length<2)continue;const header=detectHeaderRow(matrix),headers=header.headers,dataRows=matrix.slice(header.headerRowIndex+1),inference=inferColumnMapping(headers,dataRows.slice(0,25)),nonEmptyRows=dataRows.filter(r=>Array.isArray(r)&&r.some(v=>clean(v))).length;if(!nonEmptyRows)continue;sheets.push({name,headerRowIndex:header.headerRowIndex,firstDataRow:header.headerRowIndex+2,headers,dataRows,rowCount:nonEmptyRows,inference});}if(!sheets.length)throw parserError(PARSER_ERRORS.NO_USABLE_SHEETS,'No usable SIRE data sheets were detected in this workbook.');return{name:file?.name||'SIRE.xlsx',sheetCount:sheets.length,totalRows:sheets.reduce((n,s)=>n+s.rowCount,0),sheets};}
